#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust 'Model comparison - linear model - pi questions - descent methods - select train.ipynb'
jupyter trust 'Model comparison - linear model - pi questions - descent methods - select val.ipynb'
